version: '3.8'

networks:
  rede-privada:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24 # <--- Altere aqui

services:
  vps:
    build: .
    container_name: vps_proxy
    ports:
      - "3000:3000"
    environment:
      - SERVER2_URL=https://10.10.0.2:8080 # <--- Altere o IP do server2 aqui também
      - CLIENT_ID=vps_id
      - CLIENT_SECRET=super_secret_key_123
    networks:
      rede-privada:
        ipv4_address: 10.10.0.1 # <--- Altere aqui
    volumes:
      - ./certs/server2.crt:/app/certs/server2.crt:ro