version: '3.8'

networks:
  rede-privada:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

services:
  vps:
    build: .
    container_name: vps_proxy
    ports:
      - "3000:3000"
    environment:
      - SERVER2_URL=https://172.25.0.2:8080
      - CLIENT_ID=vps_id
      - CLIENT_SECRET=super_secret_key_123
    networks:
      rede-privada:
        ipv4_address: 172.25.0.1
    volumes:
      - ./certs/server2.crt:/app/certs/server2.crt:ro