version: '3.8'

networks:
  rede-privada:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  server2:
    build: .
    container_name: server2_api
    networks:
      rede-privada:
        ipv4_address: 192.168.100.2  # IP fixo do server2
    volumes:
      - ./certs/server2.crt:/app/certs/server2.crt:ro
      - ./certs/server2.key:/app/certs/server2.key:ro