version: '3.8'

networks:
  rede-privada:
    driver: bridge

services:
  server2:
    build: .
    container_name: server2_api
    ports:
      - "8080:8080"
    networks:
      - rede-privada
    volumes:
      - ./certs/server2.crt:/app/certs/server2.crt:ro
      - ./certs/server2.key:/app/certs/server2.key:ro